export const DEFAULT_COUNTRY_CODE = "MY";

export const COUNTRIES: ReadonlyArray<{
	code: string;
	name: string;
	nationality: string;
}> = [
	{ code: "MY", name: "Malaysia", nationality: "Malaysian" },
	{ code: "SG", name: "Singapore", nationality: "Singaporean" },
	{ code: "ID", name: "Indonesia", nationality: "Indonesian" },
	{ code: "TH", name: "Thailand", nationality: "Thai" },
	{ code: "PH", name: "Philippines", nationality: "Filipino" },
	{ code: "VN", name: "Vietnam", nationality: "Vietnamese" },
	{ code: "BN", name: "Brunei", nationality: "Bruneian" },
	{ code: "KH", name: "Cambodia", nationality: "Cambodian" },
	{ code: "LA", name: "Laos", nationality: "Lao" },
	{ code: "MM", name: "Myanmar", nationality: "Burmese" },
	{ code: "TL", name: "Timor-Leste", nationality: "Timorese" },
	{ code: "CN", name: "China", nationality: "Chinese" },
	{ code: "HK", name: "Hong Kong", nationality: "Hongkonger" },
	{ code: "TW", name: "Taiwan", nationality: "Taiwanese" },
	{ code: "MO", name: "Macau", nationality: "Macanese" },
	{ code: "JP", name: "Japan", nationality: "Japanese" },
	{ code: "KR", name: "South Korea", nationality: "South Korean" },
	{ code: "KP", name: "North Korea", nationality: "North Korean" },
	{ code: "MN", name: "Mongolia", nationality: "Mongolian" },
	{ code: "IN", name: "India", nationality: "Indian" },
	{ code: "PK", name: "Pakistan", nationality: "Pakistani" },
	{ code: "BD", name: "Bangladesh", nationality: "Bangladeshi" },
	{ code: "LK", name: "Sri Lanka", nationality: "Sri Lankan" },
	{ code: "NP", name: "Nepal", nationality: "Nepali" },
	{ code: "BT", name: "Bhutan", nationality: "Bhutanese" },
	{ code: "MV", name: "Maldives", nationality: "Maldivian" },
	{ code: "AF", name: "Afghanistan", nationality: "Afghan" },
	{ code: "IR", name: "Iran", nationality: "Iranian" },
	{ code: "IQ", name: "Iraq", nationality: "Iraqi" },
	{ code: "IL", name: "Israel", nationality: "Israeli" },
	{ code: "PS", name: "Palestine", nationality: "Palestinian" },
	{ code: "JO", name: "Jordan", nationality: "Jordanian" },
	{ code: "LB", name: "Lebanon", nationality: "Lebanese" },
	{ code: "SY", name: "Syria", nationality: "Syrian" },
	{ code: "SA", name: "Saudi Arabia", nationality: "Saudi" },
	{ code: "AE", name: "United Arab Emirates", nationality: "Emirati" },
	{ code: "QA", name: "Qatar", nationality: "Qatari" },
	{ code: "BH", name: "Bahrain", nationality: "Bahraini" },
	{ code: "KW", name: "Kuwait", nationality: "Kuwaiti" },
	{ code: "OM", name: "Oman", nationality: "Omani" },
	{ code: "YE", name: "Yemen", nationality: "Yemeni" },
	{ code: "TR", name: "Turkey", nationality: "Turkish" },
	{ code: "CY", name: "Cyprus", nationality: "Cypriot" },
	{ code: "AM", name: "Armenia", nationality: "Armenian" },
	{ code: "AZ", name: "Azerbaijan", nationality: "Azerbaijani" },
	{ code: "GE", name: "Georgia", nationality: "Georgian" },
	{ code: "KZ", name: "Kazakhstan", nationality: "Kazakh" },
	{ code: "KG", name: "Kyrgyzstan", nationality: "Kyrgyz" },
	{ code: "TJ", name: "Tajikistan", nationality: "Tajik" },
	{ code: "TM", name: "Turkmenistan", nationality: "Turkmen" },
	{ code: "UZ", name: "Uzbekistan", nationality: "Uzbek" },
	{ code: "RU", name: "Russia", nationality: "Russian" },
	{ code: "UA", name: "Ukraine", nationality: "Ukrainian" },
	{ code: "BY", name: "Belarus", nationality: "Belarusian" },
	{ code: "MD", name: "Moldova", nationality: "Moldovan" },
	{ code: "PL", name: "Poland", nationality: "Polish" },
	{ code: "CZ", name: "Czech Republic", nationality: "Czech" },
	{ code: "SK", name: "Slovakia", nationality: "Slovak" },
	{ code: "HU", name: "Hungary", nationality: "Hungarian" },
	{ code: "RO", name: "Romania", nationality: "Romanian" },
	{ code: "BG", name: "Bulgaria", nationality: "Bulgarian" },
	{ code: "RS", name: "Serbia", nationality: "Serbian" },
	{ code: "HR", name: "Croatia", nationality: "Croatian" },
	{ code: "SI", name: "Slovenia", nationality: "Slovenian" },
	{ code: "BA", name: "Bosnia and Herzegovina", nationality: "Bosnian" },
	{ code: "ME", name: "Montenegro", nationality: "Montenegrin" },
	{ code: "MK", name: "North Macedonia", nationality: "Macedonian" },
	{ code: "AL", name: "Albania", nationality: "Albanian" },
	{ code: "XK", name: "Kosovo", nationality: "Kosovar" },
	{ code: "GR", name: "Greece", nationality: "Greek" },
	{ code: "IT", name: "Italy", nationality: "Italian" },
	{ code: "MT", name: "Malta", nationality: "Maltese" },
	{ code: "SM", name: "San Marino", nationality: "Sammarinese" },
	{ code: "VA", name: "Vatican City", nationality: "Vatican" },
	{ code: "ES", name: "Spain", nationality: "Spanish" },
	{ code: "PT", name: "Portugal", nationality: "Portuguese" },
	{ code: "AD", name: "Andorra", nationality: "Andorran" },
	{ code: "FR", name: "France", nationality: "French" },
	{ code: "MC", name: "Monaco", nationality: "Monégasque" },
	{ code: "BE", name: "Belgium", nationality: "Belgian" },
	{ code: "NL", name: "Netherlands", nationality: "Dutch" },
	{ code: "LU", name: "Luxembourg", nationality: "Luxembourgish" },
	{ code: "DE", name: "Germany", nationality: "German" },
	{ code: "AT", name: "Austria", nationality: "Austrian" },
	{ code: "CH", name: "Switzerland", nationality: "Swiss" },
	{ code: "LI", name: "Liechtenstein", nationality: "Liechtensteiner" },
	{ code: "GB", name: "United Kingdom", nationality: "British" },
	{ code: "IE", name: "Ireland", nationality: "Irish" },
	{ code: "IS", name: "Iceland", nationality: "Icelandic" },
	{ code: "NO", name: "Norway", nationality: "Norwegian" },
	{ code: "SE", name: "Sweden", nationality: "Swedish" },
	{ code: "FI", name: "Finland", nationality: "Finnish" },
	{ code: "DK", name: "Denmark", nationality: "Danish" },
	{ code: "EE", name: "Estonia", nationality: "Estonian" },
	{ code: "LV", name: "Latvia", nationality: "Latvian" },
	{ code: "LT", name: "Lithuania", nationality: "Lithuanian" },
	{ code: "CA", name: "Canada", nationality: "Canadian" },
	{ code: "US", name: "United States", nationality: "American" },
	{ code: "MX", name: "Mexico", nationality: "Mexican" },
	{ code: "GT", name: "Guatemala", nationality: "Guatemalan" },
	{ code: "BZ", name: "Belize", nationality: "Belizean" },
	{ code: "SV", name: "El Salvador", nationality: "Salvadoran" },
	{ code: "HN", name: "Honduras", nationality: "Honduran" },
	{ code: "NI", name: "Nicaragua", nationality: "Nicaraguan" },
	{ code: "CR", name: "Costa Rica", nationality: "Costa Rican" },
	{ code: "PA", name: "Panama", nationality: "Panamanian" },
	{ code: "CU", name: "Cuba", nationality: "Cuban" },
	{ code: "JM", name: "Jamaica", nationality: "Jamaican" },
	{ code: "HT", name: "Haiti", nationality: "Haitian" },
	{ code: "DO", name: "Dominican Republic", nationality: "Dominican" },
	{ code: "PR", name: "Puerto Rico", nationality: "Puerto Rican" },
	{ code: "TT", name: "Trinidad and Tobago", nationality: "Trinidadian" },
	{ code: "BB", name: "Barbados", nationality: "Barbadian" },
	{ code: "BS", name: "Bahamas", nationality: "Bahamian" },
	{ code: "CO", name: "Colombia", nationality: "Colombian" },
	{ code: "VE", name: "Venezuela", nationality: "Venezuelan" },
	{ code: "GY", name: "Guyana", nationality: "Guyanese" },
	{ code: "SR", name: "Suriname", nationality: "Surinamese" },
	{ code: "EC", name: "Ecuador", nationality: "Ecuadorian" },
	{ code: "PE", name: "Peru", nationality: "Peruvian" },
	{ code: "BO", name: "Bolivia", nationality: "Bolivian" },
	{ code: "BR", name: "Brazil", nationality: "Brazilian" },
	{ code: "PY", name: "Paraguay", nationality: "Paraguayan" },
	{ code: "UY", name: "Uruguay", nationality: "Uruguayan" },
	{ code: "AR", name: "Argentina", nationality: "Argentine" },
	{ code: "CL", name: "Chile", nationality: "Chilean" },
	{ code: "AU", name: "Australia", nationality: "Australian" },
	{ code: "NZ", name: "New Zealand", nationality: "New Zealander" },
	{ code: "PG", name: "Papua New Guinea", nationality: "Papua New Guinean" },
	{ code: "FJ", name: "Fiji", nationality: "Fijian" },
	{ code: "SB", name: "Solomon Islands", nationality: "Solomon Islander" },
	{ code: "VU", name: "Vanuatu", nationality: "Ni-Vanuatu" },
	{ code: "NC", name: "New Caledonia", nationality: "New Caledonian" },
	{ code: "PF", name: "French Polynesia", nationality: "French Polynesian" },
	{ code: "WS", name: "Samoa", nationality: "Samoan" },
	{ code: "TO", name: "Tonga", nationality: "Tongan" },
	{ code: "KI", name: "Kiribati", nationality: "I-Kiribati" },
	{ code: "TV", name: "Tuvalu", nationality: "Tuvaluan" },
	{ code: "NR", name: "Nauru", nationality: "Nauruan" },
	{ code: "PW", name: "Palau", nationality: "Palauan" },
	{ code: "FM", name: "Micronesia", nationality: "Micronesian" },
	{ code: "MH", name: "Marshall Islands", nationality: "Marshallese" },
	{ code: "EG", name: "Egypt", nationality: "Egyptian" },
	{ code: "LY", name: "Libya", nationality: "Libyan" },
	{ code: "TN", name: "Tunisia", nationality: "Tunisian" },
	{ code: "DZ", name: "Algeria", nationality: "Algerian" },
	{ code: "MA", name: "Morocco", nationality: "Moroccan" },
	{ code: "SD", name: "Sudan", nationality: "Sudanese" },
	{ code: "SS", name: "South Sudan", nationality: "South Sudanese" },
	{ code: "ET", name: "Ethiopia", nationality: "Ethiopian" },
	{ code: "ER", name: "Eritrea", nationality: "Eritrean" },
	{ code: "DJ", name: "Djibouti", nationality: "Djiboutian" },
	{ code: "SO", name: "Somalia", nationality: "Somali" },
	{ code: "KE", name: "Kenya", nationality: "Kenyan" },
	{ code: "UG", name: "Uganda", nationality: "Ugandan" },
	{ code: "RW", name: "Rwanda", nationality: "Rwandan" },
	{ code: "BI", name: "Burundi", nationality: "Burundian" },
	{ code: "TZ", name: "Tanzania", nationality: "Tanzanian" },
	{ code: "MW", name: "Malawi", nationality: "Malawian" },
	{ code: "MZ", name: "Mozambique", nationality: "Mozambican" },
	{ code: "ZM", name: "Zambia", nationality: "Zambian" },
	{ code: "ZW", name: "Zimbabwe", nationality: "Zimbabwean" },
	{ code: "BW", name: "Botswana", nationality: "Motswana" },
	{ code: "NA", name: "Namibia", nationality: "Namibian" },
	{ code: "ZA", name: "South Africa", nationality: "South African" },
	{ code: "LS", name: "Lesotho", nationality: "Mosotho" },
	{ code: "SZ", name: "Eswatini", nationality: "Swazi" },
	{ code: "AO", name: "Angola", nationality: "Angolan" },
	{ code: "CG", name: "Republic of the Congo", nationality: "Congolese" },
	{ code: "CD", name: "DR Congo", nationality: "Congolese" },
	{ code: "CF", name: "Central African Republic", nationality: "Central African" },
	{ code: "CM", name: "Cameroon", nationality: "Cameroonian" },
	{ code: "GQ", name: "Equatorial Guinea", nationality: "Equatoguinean" },
	{ code: "GA", name: "Gabon", nationality: "Gabonese" },
	{ code: "ST", name: "São Tomé and Príncipe", nationality: "São Toméan" },
	{ code: "TD", name: "Chad", nationality: "Chadian" },
	{ code: "NE", name: "Niger", nationality: "Nigerien" },
	{ code: "NG", name: "Nigeria", nationality: "Nigerian" },
	{ code: "BJ", name: "Benin", nationality: "Beninese" },
	{ code: "TG", name: "Togo", nationality: "Togolese" },
	{ code: "GH", name: "Ghana", nationality: "Ghanaian" },
	{ code: "BF", name: "Burkina Faso", nationality: "Burkinabé" },
	{ code: "CI", name: "Côte d'Ivoire", nationality: "Ivorian" },
	{ code: "LR", name: "Liberia", nationality: "Liberian" },
	{ code: "SL", name: "Sierra Leone", nationality: "Sierra Leonean" },
	{ code: "GN", name: "Guinea", nationality: "Guinean" },
	{ code: "GW", name: "Guinea-Bissau", nationality: "Bissau-Guinean" },
	{ code: "SN", name: "Senegal", nationality: "Senegalese" },
	{ code: "GM", name: "Gambia", nationality: "Gambian" },
	{ code: "ML", name: "Mali", nationality: "Malian" },
	{ code: "MR", name: "Mauritania", nationality: "Mauritanian" },
	{ code: "CV", name: "Cape Verde", nationality: "Cabo Verdean" },
	{ code: "MG", name: "Madagascar", nationality: "Malagasy" },
	{ code: "MU", name: "Mauritius", nationality: "Mauritian" },
	{ code: "SC", name: "Seychelles", nationality: "Seychellois" },
	{ code: "KM", name: "Comoros", nationality: "Comorian" },
];

export const COUNTRY_CODES = COUNTRIES.map((c) => c.code) as ReadonlyArray<
	(typeof COUNTRIES)[number]["code"]
>;

const COUNTRY_BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

export function countryNameForCode(code: string | null | undefined): string {
	if (!code) return "—";
	return COUNTRY_BY_CODE.get(code.toUpperCase())?.name ?? code;
}

export function nationalityForCode(code: string | null | undefined): string {
	if (!code) return "—";
	const entry = COUNTRY_BY_CODE.get(code.toUpperCase());
	return entry?.nationality ?? entry?.name ?? code;
}

export function isValidCountryCode(value: string | null | undefined): boolean {
	if (!value) return false;
	return COUNTRY_BY_CODE.has(value.toUpperCase());
}

export function flagForCountryCode(code: string | null | undefined): string {
	if (!code || code.length !== 2) return "";
	const upper = code.toUpperCase();
	const a = upper.charCodeAt(0);
	const b = upper.charCodeAt(1);
	if (a < 65 || a > 90 || b < 65 || b > 90) return "";
	return String.fromCodePoint(0x1f1e6 + (a - 65), 0x1f1e6 + (b - 65));
}
