-- prototype_dump/schema_history.sql
-- Generated by concatenating supabase/migrations/*.sql from the prototype repo.
-- This is the actual schema history of the v1 prototype — 24 incremental migrations.
-- REFERENCE ONLY. The new repo's canonical schema is docs/schema/initial_schema.sql.
--

-- ============================================================
-- FILE: 20260313000001_initial_schema.sql
-- ============================================================
-- =============================================================================
-- KumoDent / Aoikumo Schema — Supabase Migration
-- Generated from: all Aoikumo Sales, Payment, Inventory, Customer,
--   Appointment, Employee, Clinical, Commission and Other report CSVs (109 reports)
-- =============================================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- =============================================================================
-- REFERENCE / MASTER TABLES
-- =============================================================================

-- Outlets (branches)
-- Source: Sales By Outlet Report, Sales Detailed Report
create table if not exists outlets (
  id           uuid primary key default uuid_generate_v4(),
  name         text not null unique,
  code         text,
  address1     text,
  address2     text,
  city         text,
  state        text,
  postcode     text,
  country      text default 'Malaysia',
  phone        text,
  email        text,
  is_active    boolean default true,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

-- Employees / Staff
-- Source: Sales By Employee Report, Employee Listing Report
-- Captured columns: Employee ID, Name, Identification #, Email, Date of Birth,
--   Gender, Contact #, Role, Position, Start Date, Main Outlet, Secondary Outlet,
--   Country, State, City, kumoSan Access, Web Access, Bookable, Online Bookable, Username
create table if not exists employees (
  id                  uuid primary key default uuid_generate_v4(),
  employee_code       text unique,              -- "Employee ID" from report
  name                text not null,
  identification_no   text,
  email               text,
  date_of_birth       date,
  gender              text,
  contact_no          text,
  role                text,                     -- Therapist, Consultant, Admin, etc.
  position            text,
  start_date          date,
  main_outlet_id      uuid references outlets(id),
  secondary_outlet_id uuid references outlets(id),
  country             text default 'Malaysia',
  state               text,
  city                text,
  username            text,
  kumosan_access      boolean default false,    -- "kumoSan Access?"
  web_access          boolean default false,    -- "Web Access?"
  bookable            boolean default true,     -- "Bookable?"
  online_bookable     boolean default false,    -- "Online Bookable?"
  sales_target        numeric(10,2) default 0,  -- from Sales By Employee
  handson_points      numeric(10,2) default 0,  -- from Sales By Employee
  is_active           boolean default true,
  created_at          timestamptz default now(),
  updated_at          timestamptz default now()
);

-- Services catalogue
-- Source: Service Sales Report, Service Listing by Outlet
create table if not exists services (
  id            uuid primary key default uuid_generate_v4(),
  sku           text not null unique,
  name          text not null,
  category      text,
  type          text default 'Standard',        -- Standard, Premium
  duration_min  int,
  price         numeric(10,2) not null default 0,
  is_active     boolean default true,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- Products catalogue
-- Source: Item Sales Report, Stock Movement Report
create table if not exists products (
  id            uuid primary key default uuid_generate_v4(),
  sku           text not null unique,
  name          text not null,
  brand         text,
  category      text,
  uom           text default 'PCS',             -- Unit of Measure
  cost_price    numeric(10,2) default 0,
  sell_price    numeric(10,2) default 0,
  stock_qty     numeric(10,3) default 0,
  reorder_level numeric(10,3) default 0,
  supplier_id   uuid,
  is_active     boolean default true,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- Mix & Match package definitions
-- Source: Mix and Match Sales Report
create table if not exists mix_match_packages (
  id            uuid primary key default uuid_generate_v4(),
  sku           text not null unique,           -- "SKU" (MM-001)
  name          text not null,                  -- "MM Name"
  total_price   numeric(10,2) default 0,
  sessions      int default 0,                  -- total sessions included
  is_active     boolean default true,
  created_at    timestamptz default now()
);

-- Credit voucher schemes
-- Source: Sales Voucher Use Report, Credit Voucher Sales Report
create table if not exists voucher_schemes (
  id            uuid primary key default uuid_generate_v4(),
  name          text not null,                  -- "Voucher Name"
  batch_no      int,                            -- "Voucher Batch"
  voucher_type  text default 'MYR',             -- MYR or %
  value         numeric(10,2) default 0,        -- "Voucher Value"
  expiry_date   date,
  is_active     boolean default true,
  created_at    timestamptz default now()
);

-- Discount schemes
-- Source: Sales Discount Use Report
create table if not exists discount_schemes (
  id            uuid primary key default uuid_generate_v4(),
  name          text not null,                  -- "Discount Name"
  type          text default 'PERCENTAGE',      -- PERCENTAGE, FIXED
  value         numeric(10,2) default 0,
  assignment    text,                           -- who can assign
  is_active     boolean default true,
  created_at    timestamptz default now()
);

-- Suppliers
-- Source: Supplier Listing Report, Purchase Orders Report
create table if not exists suppliers (
  id            uuid primary key default uuid_generate_v4(),
  name          text not null,
  code          text unique,
  contact       text,
  email         text,
  phone         text,
  address       text,
  is_active     boolean default true,
  created_at    timestamptz default now()
);

-- =============================================================================
-- CUSTOMER TABLE
-- =============================================================================

-- Customers / Members
-- Source: Sales Detailed, Customer Reports, Customer Lead Generation
-- Captured columns: ID, Customer, Membership, Phone, Total Appt, BP, BP Wallet,
--   Cash wallet, Collection, CV Total, LP, CV Wallet, Sales, Case note, Follow Up,
--   Medical Certificate, E-Form, Documents, Records
create table if not exists customers (
  id                    uuid primary key default uuid_generate_v4(),
  membership_no         text not null unique,   -- PK from Aoikumo (e.g. ANB260001)
  name                  text not null,
  first_name            text,
  last_name             text,
  salutation            text,                   -- Mr, Ms, Mrs, Dr
  gender                text,
  identification_no     text,                   -- IC / Passport
  phone                 text,
  phone2                text,
  email                 text,
  date_of_birth         date,
  membership_type       text default 'No Membership', -- GOLD MEMBER, VIP MEMBER, etc.
  home_outlet_id        uuid references outlets(id),
  consultant_id         uuid references employees(id),
  -- Address
  address1              text,
  address2              text,
  city                  text,
  state                 text,
  postcode              text,
  country               text default 'Malaysia',
  -- Wallet / loyalty balances (denormalised for fast read)
  cash_wallet_balance   numeric(10,2) default 0,
  beauti_points_balance numeric(10,2) default 0,
  credit_voucher_balance numeric(10,2) default 0,
  loyalty_points_balance numeric(10,2) default 0,
  -- Preferences
  source                text,                   -- Walk In, Referral, ADS, Online Booking
  preferred_language    text default 'English',
  opt_in_notifications  boolean default true,
  opt_in_marketing      boolean default true,
  is_vip                boolean default false,
  -- Medical
  allergies             text,
  medical_notes         text,
  -- Stats (denormalised, updated by trigger or job)
  total_appointments    int default 0,
  total_sales           numeric(10,2) default 0,
  -- Meta
  join_date             date,
  created_at            timestamptz default now(),
  updated_at            timestamptz default now()
);

-- =============================================================================
-- APPOINTMENTS
-- =============================================================================

-- Appointments
-- Source: Appointments Detailed Report
-- Columns: Date, Time, Booking Ref, Customer, Membership #, Phone,
--   Service, Staff/Therapist, Chair/Room, Duration, Status, Payment Status, Notes
create table if not exists appointments (
  id               uuid primary key default uuid_generate_v4(),
  booking_ref      text not null unique,         -- e.g. BREF-001001
  customer_id      uuid references customers(id),
  customer_name    text,                          -- denormalised
  customer_phone   text,
  membership_no    text,
  service_id       uuid references services(id),
  service_name     text,
  service_code     text,
  employee_id      uuid references employees(id), -- therapist/dentist
  employee_name    text,
  outlet_id        uuid references outlets(id),
  chair            text,                          -- chair / room
  start_time       timestamptz not null,
  end_time         timestamptz,
  duration_min     int,
  status           text default 'pending',        -- pending, confirmed, completed, cancelled, no-show
  payment_status   text default 'unpaid',         -- unpaid, paid, partial
  tags             text[],
  notes            text,
  case_notes       text,
  follow_up        text,
  created_by       text,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

-- Appointment changes log
-- Source: Appointments Change Report
create table if not exists appointment_changes (
  id               uuid primary key default uuid_generate_v4(),
  appointment_id   uuid references appointments(id),
  booking_ref      text,
  changed_at       timestamptz,
  changed_by       text,
  field_changed    text,
  old_value        text,
  new_value        text,
  reason           text
);

-- =============================================================================
-- SALES (CORE TRANSACTION TABLES)
-- =============================================================================

-- Sales Orders (header)
-- Source: Sales Detailed Report (27 columns — full schema)
create table if not exists sales (
  id               uuid primary key default uuid_generate_v4(),
  so_number        text not null unique,          -- SO/1/000356 (PK from Aoikumo)
  type             text default 'STORE',          -- STORE, CV, BP, CW, MM, EVENT, ADMIN
  outlet_id        uuid references outlets(id),
  outlet_name      text,
  customer_id      uuid references customers(id),
  customer_name    text,
  identification_no text,
  customer_phone   text,
  membership_no    text,
  membership_type  text,
  payee_origin     text default 'STORE',
  -- Financials (all match Aoikumo Sales Detailed columns)
  sub_total        numeric(10,2) default 0,
  voucher          numeric(10,2) default 0,       -- CV applied
  discount         numeric(10,2) default 0,       -- discount applied
  cw               numeric(10,2) default 0,       -- cash wallet used
  cw_tax           numeric(10,2) default 0,
  gross            numeric(10,2) default 0,       -- sub_total - discount - voucher - cw
  tax_value        numeric(10,2) default 0,       -- SST/GST
  cancelled        numeric(10,2) default 0,
  cw_cancelled     numeric(10,2) default 0,
  rounding         numeric(10,2) default 0,
  nett             numeric(10,2) default 0,       -- net payable
  payment_to_date  numeric(10,2) default 0,
  outstanding      numeric(10,2) default 0,
  -- Staff
  sales_person     text,
  processed_by     text,
  created_by       text,
  -- Notes
  sales_notes      text,
  remarks          text,
  -- Status
  status           text default 'completed',      -- completed, cancelled, pending
  -- Timestamps
  sale_date        date,
  sale_time        time,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

-- Sale Items (lines)
-- Source: Item Sales Report, Service Sales Report
create table if not exists sale_items (
  id             uuid primary key default uuid_generate_v4(),
  so_number      text not null references sales(so_number),
  sku            text,
  item_name      text not null,
  brand          text,
  type           text,                             -- Product, Service, CV, BP, MM, Promo, Bundle
  quantity       int default 1,
  unit_price     numeric(10,2) default 0,
  unit_discount  numeric(10,2) default 0,
  total_price    numeric(10,2) default 0,
  uom            text default 'SESSION',
  redeemed       int default 0,
  cancelled      boolean default false,
  created_at     timestamptz default now()
);

-- Payments
-- Source: Payment Detailed Report
-- Columns: Date, Time, Invoice #, SO #, Outlet, Customer, Identification #,
--   Phone, Membership #, Type, Payment Method, Amount, Bank, Trace #,
--   Approval Code, Reference #, Outstanding, Processed By
create table if not exists payments (
  id             uuid primary key default uuid_generate_v4(),
  invoice_no     text unique,                     -- INV/1/000356
  so_number      text references sales(so_number),
  outlet_id      uuid references outlets(id),
  customer_name  text,
  identification_no text,
  customer_phone text,
  membership_no  text,
  payment_date   date,
  payment_time   time,
  payment_mode   text,                             -- Cash, Card, Online Transfer, CW, CV, BP
  payment_type   text,                             -- Visa, Mastercard, FPX, e-wallet name
  bank           text,
  amount         numeric(10,2) default 0,
  trace_no       text,
  approval_code  text,
  ref_no         text,
  outstanding    numeric(10,2) default 0,
  payee_origin   text,
  remarks        text,
  processed_by   text,
  created_at     timestamptz default now()
);

-- Sales Cancellations (Credit Notes)
-- Source: Sales Cancellation Report (17 columns — full schema)
create table if not exists cancellations (
  id                   uuid primary key default uuid_generate_v4(),
  cn_number            text not null unique,       -- CN/1/000012
  cn_date              date,
  cn_time              time,
  so_number            text references sales(so_number),
  so_date              date,
  so_time              time,
  cancellation_outlet  text,
  so_creation_outlet   text,
  customer_name        text,
  identification_no    text,
  customer_phone       text,
  amount               numeric(10,2) default 0,
  tax                  numeric(10,2) default 0,
  tax_rate             text default '0%',
  processed_by         text,
  sales_person         text,
  remarks              text,
  created_at           timestamptz default now()
);

-- Discounts Used per line item
-- Source: Sales Discount Use Report (19 columns — full schema)
create table if not exists discounts_used (
  id               uuid primary key default uuid_generate_v4(),
  so_number        text references sales(so_number),
  discount_date    date,
  discount_time    time,
  customer_name    text,
  identification_no text,
  customer_phone   text,
  membership_no    text,
  membership_type  text,
  sku              text,
  item_name        text,
  unit_price       numeric(10,2) default 0,
  unit_discount    numeric(10,2) default 0,
  quantity         int default 1,
  total_price      numeric(10,2) default 0,
  total_discount   numeric(10,2) default 0,
  nett_price       numeric(10,2) default 0,
  discount_name    text,
  assignment       text,
  processed_by     text,
  created_at       timestamptz default now()
);

-- =============================================================================
-- LOYALTY / WALLET TABLES
-- =============================================================================

-- Credit Vouchers
-- Source: Credit Voucher Sales Report, Sales Voucher Use Report
create table if not exists credit_vouchers (
  id             uuid primary key default uuid_generate_v4(),
  cv_number      text not null unique,             -- CV/1/000045
  so_number      text references sales(so_number),
  so_date        date,
  so_time        time,
  cv_name        text,                             -- scheme name
  voucher_batch  int,
  voucher_no     text,                             -- voucher code
  voucher_type   text default 'MYR',
  voucher_value  numeric(10,2) default 0,
  item_redeemed  text,
  paid           numeric(10,2) default 0,
  type           text,                             -- VOUCHER, REDEMPTION
  customer_name  text,
  membership_no  text,
  sales_person   text,
  created_by     text,
  created_at     timestamptz default now()
);

-- Beauti Points transactions
-- Source: Beauti Points Sales Report (12 columns — full schema)
create table if not exists beauti_points (
  id           uuid primary key default uuid_generate_v4(),
  bp_number    text not null unique,               -- BP/1/000088
  so_number    text references sales(so_number),
  so_date      date,
  so_time      time,
  bp_date      date,
  bp_time      time,
  customer_name text,
  identification_no text,
  phone        text,
  membership_no text,
  sales_person text,
  paid_bp      numeric(10,2) default 0,
  created_at   timestamptz default now()
);

-- Cash Wallet transactions
-- Source: Cash Wallet Sales Report (15 columns — full schema)
create table if not exists cash_wallet (
  id             uuid primary key default uuid_generate_v4(),
  so_number      text references sales(so_number),
  cw_date        date,
  cw_time        time,
  type           text,                             -- CW (top-up), CW_USE (redemption)
  outlet_id      uuid references outlets(id),
  customer_name  text,
  membership_no  text,
  membership_type text,
  cw_amount      numeric(10,2) default 0,
  gross          numeric(10,2) default 0,
  nett           numeric(10,2) default 0,
  payment_to_date numeric(10,2) default 0,
  outstanding    numeric(10,2) default 0,
  sales_person   text,
  created_at     timestamptz default now()
);

-- Mix & Match package purchases
-- Source: Mix and Match Sales Report (8 columns summary + detail)
create table if not exists mix_match_sales (
  id               uuid primary key default uuid_generate_v4(),
  so_number        text references sales(so_number),
  package_id       uuid references mix_match_packages(id),
  sku              text,
  mm_name          text,
  quantity         int default 1,
  cancelled_qty    int default 0,
  sales_amount     numeric(10,2) default 0,
  average_sales    numeric(10,2) default 0,
  payment_to_date  numeric(10,2) default 0,
  outstanding      numeric(10,2) default 0,
  customer_name    text,
  membership_no    text,
  purchased_qty    int default 0,                  -- sessions purchased
  redeemed_qty     int default 0,                  -- sessions redeemed
  balance_qty      int default 0,                  -- sessions remaining
  created_at       timestamptz default now()
);

-- =============================================================================
-- INVENTORY
-- =============================================================================

-- Stock movements
-- Source: Stock Movement Report, Stock Movement Detailed Report
create table if not exists stock_movements (
  id             uuid primary key default uuid_generate_v4(),
  movement_date  date,
  movement_time  time,
  product_id     uuid references products(id),
  sku            text,
  product_name   text,
  brand          text,
  category       text,
  outlet_id      uuid references outlets(id),
  movement_type  text,                             -- IN, OUT, ADJUST, TRANSFER
  reference_no   text,                             -- PO#, SO#, or Transfer Order#
  opening_qty    numeric(10,3) default 0,
  in_qty         numeric(10,3) default 0,
  out_qty        numeric(10,3) default 0,
  closing_qty    numeric(10,3) default 0,
  uom            text,
  unit_cost      numeric(10,2) default 0,
  created_by     text,
  created_at     timestamptz default now()
);

-- Purchase Orders
-- Source: Purchase Orders Report
create table if not exists purchase_orders (
  id             uuid primary key default uuid_generate_v4(),
  po_number      text not null unique,
  po_date        date,
  supplier_id    uuid references suppliers(id),
  outlet_id      uuid references outlets(id),
  status         text default 'pending',           -- pending, received, cancelled
  total_amount   numeric(10,2) default 0,
  received_date  date,
  created_by     text,
  remarks        text,
  created_at     timestamptz default now()
);

-- Purchase order lines
create table if not exists purchase_order_items (
  id              uuid primary key default uuid_generate_v4(),
  po_number       text references purchase_orders(po_number),
  product_id      uuid references products(id),
  sku             text,
  product_name    text,
  quantity        numeric(10,3) default 0,
  unit_cost       numeric(10,2) default 0,
  total_cost      numeric(10,2) default 0,
  received_qty    numeric(10,3) default 0,
  created_at      timestamptz default now()
);

-- =============================================================================
-- COMMISSION & INCENTIVES
-- =============================================================================

-- Commission records
-- Source: Commission & Incentive Reports
create table if not exists commissions (
  id               uuid primary key default uuid_generate_v4(),
  commission_month date,                           -- first day of the month
  employee_id      uuid references employees(id),
  employee_name    text,
  outlet_id        uuid references outlets(id),
  services_sales   numeric(10,2) default 0,
  products_sales   numeric(10,2) default 0,
  total_sales      numeric(10,2) default 0,
  services_commission numeric(10,2) default 0,
  products_commission numeric(10,2) default 0,
  total_commission numeric(10,2) default 0,
  incentive        numeric(10,2) default 0,
  payout           numeric(10,2) default 0,
  created_at       timestamptz default now()
);

-- =============================================================================
-- CLINICAL / MEDICAL RECORDS
-- =============================================================================

-- Case Notes
-- Source: Case Notes Report
create table if not exists case_notes (
  id               uuid primary key default uuid_generate_v4(),
  appointment_id   uuid references appointments(id),
  customer_id      uuid references customers(id),
  customer_name    text,
  membership_no    text,
  note_date        date,
  note_time        time,
  content          text,
  employee_id      uuid references employees(id),
  created_by       text,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

-- Prescriptions
-- Source: Prescription Report
create table if not exists prescriptions (
  id               uuid primary key default uuid_generate_v4(),
  appointment_id   uuid references appointments(id),
  customer_id      uuid references customers(id),
  customer_name    text,
  prescription_date date,
  medication       text,
  dosage           text,
  frequency        text,
  duration         text,
  notes            text,
  prescribed_by    text,
  created_at       timestamptz default now()
);

-- Vaccinations
-- Source: Vaccination Report
create table if not exists vaccinations (
  id               uuid primary key default uuid_generate_v4(),
  customer_id      uuid references customers(id),
  customer_name    text,
  membership_no    text,
  vaccine_name     text,
  batch_no         text,
  administered_date date,
  next_due_date    date,
  administered_by  text,
  outlet_id        uuid references outlets(id),
  created_at       timestamptz default now()
);

-- =============================================================================
-- OTHER OPERATIONAL TABLES
-- =============================================================================

-- Petty Cash
-- Source: Petty Cash Report (Sales Tab)
create table if not exists petty_cash (
  id             uuid primary key default uuid_generate_v4(),
  cash_date      date not null,
  cash_time      time,
  outlet_id      uuid references outlets(id),
  type           text not null,                    -- IN, OUT
  amount         numeric(10,2) not null default 0,
  description    text,
  created_by     text,
  created_at     timestamptz default now()
);

-- Vouchers generated and expiry tracking
-- Source: Voucher Generated & Expiry Report
create table if not exists vouchers_generated (
  id             uuid primary key default uuid_generate_v4(),
  scheme_id      uuid references voucher_schemes(id),
  voucher_name   text,
  voucher_batch  int,
  voucher_no     text not null unique,
  customer_id    uuid references customers(id),
  customer_name  text,
  face_value     numeric(10,2) default 0,
  expiry_date    date,
  status         text default 'active',            -- active, redeemed, expired
  redeemed_date  date,
  redeemed_so    text references sales(so_number),
  created_at     timestamptz default now()
);

-- Other Charges
-- Source: Other Charges Report (17 columns — full schema)
create table if not exists other_charges (
  id             uuid primary key default uuid_generate_v4(),
  so_number      text references sales(so_number),
  charge_date    date,
  charge_time    time,
  type           text,
  outlet_id      uuid references outlets(id),
  customer_name  text,
  identification_no text,
  customer_phone text,
  membership_no  text,
  sku            text,
  item_name      text,
  sales_amount   numeric(10,2) default 0,
  payment_to_date numeric(10,2) default 0,
  outstanding    numeric(10,2) default 0,
  sales_person   text,
  status         text default 'COMPLETED',
  processed_by   text,
  created_at     timestamptz default now()
);

-- =============================================================================
-- INDEXES for performance
-- =============================================================================

create index if not exists idx_sales_so_number        on sales(so_number);
create index if not exists idx_sales_customer_id      on sales(customer_id);
create index if not exists idx_sales_sale_date        on sales(sale_date);
create index if not exists idx_sales_outlet_id        on sales(outlet_id);
create index if not exists idx_sale_items_so_number   on sale_items(so_number);
create index if not exists idx_payments_so_number     on payments(so_number);
create index if not exists idx_payments_invoice_no    on payments(invoice_no);
create index if not exists idx_appointments_customer  on appointments(customer_id);
create index if not exists idx_appointments_start     on appointments(start_time);
create index if not exists idx_appointments_employee  on appointments(employee_id);
create index if not exists idx_customers_membership   on customers(membership_no);
create index if not exists idx_customers_phone        on customers(phone);
create index if not exists idx_cancellations_so       on cancellations(so_number);
create index if not exists idx_discounts_used_so      on discounts_used(so_number);
create index if not exists idx_stock_movements_sku    on stock_movements(sku);
create index if not exists idx_stock_movements_date   on stock_movements(movement_date);

-- =============================================================================
-- ROW LEVEL SECURITY (Supabase standard — enables per-user data isolation)
-- =============================================================================

alter table outlets          enable row level security;
alter table employees        enable row level security;
alter table services         enable row level security;
alter table products         enable row level security;
alter table customers        enable row level security;
alter table appointments     enable row level security;
alter table sales            enable row level security;
alter table sale_items       enable row level security;
alter table payments         enable row level security;
alter table cancellations    enable row level security;
alter table discounts_used   enable row level security;
alter table credit_vouchers  enable row level security;
alter table beauti_points    enable row level security;
alter table cash_wallet      enable row level security;
alter table mix_match_sales  enable row level security;
alter table stock_movements  enable row level security;
alter table purchase_orders  enable row level security;
alter table commissions      enable row level security;
alter table case_notes       enable row level security;
alter table petty_cash       enable row level security;
alter table vouchers_generated enable row level security;
alter table other_charges    enable row level security;

-- Allow authenticated users full access (tighten per role in production)
create policy "Authenticated full access" on outlets          for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on employees        for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on services         for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on products         for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on customers        for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on appointments     for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on sales            for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on sale_items       for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on payments         for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on cancellations    for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on discounts_used   for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on credit_vouchers  for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on beauti_points    for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on cash_wallet      for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on mix_match_sales  for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on stock_movements  for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on purchase_orders  for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on commissions      for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on case_notes       for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on petty_cash       for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on vouchers_generated for all using (auth.role() = 'authenticated');
create policy "Authenticated full access" on other_charges    for all using (auth.role() = 'authenticated');

-- =============================================================================
-- UPDATED_AT trigger helper
-- =============================================================================

create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_outlets_updated_at
  before update on outlets for each row execute function update_updated_at();
create trigger trg_employees_updated_at
  before update on employees for each row execute function update_updated_at();
create trigger trg_services_updated_at
  before update on services for each row execute function update_updated_at();
create trigger trg_products_updated_at
  before update on products for each row execute function update_updated_at();
create trigger trg_customers_updated_at
  before update on customers for each row execute function update_updated_at();
create trigger trg_appointments_updated_at
  before update on appointments for each row execute function update_updated_at();
create trigger trg_sales_updated_at
  before update on sales for each row execute function update_updated_at();
create trigger trg_case_notes_updated_at
  before update on case_notes for each row execute function update_updated_at();

-- ============================================================
-- FILE: 20260315000001_frontend_compat.sql
-- ============================================================
-- =============================================================================
-- KumoDent Frontend Compatibility Migration
-- Makes the DB work with the frontend data model:
--   1. Creates `patients` table (text PK, matches frontend camelCase→snake_case)
--   2. Adds frontend-friendly columns to `appointments`
--   3. Grants anon / unauthenticated access so the app works without auth
-- =============================================================================

-- ── 1. Patients table (frontend-compatible, text primary key) ─────────────────
create table if not exists patients (
  id                      text primary key,
  member_id               text,
  membership_no           text,
  name                    text,
  first_name              text,
  last_name               text,
  salutation              text,
  gender                  text,
  phone                   text,
  phone2                  text,
  email                   text,
  dob                     text,
  identification_no       text,
  membership_type         text default 'No Membership',
  cash_wallet_balance     numeric(10,2) default 0,
  beauti_points_balance   numeric(10,2) default 0,
  credit_voucher_balance  numeric(10,2) default 0,
  address1                text default '',
  address2                text default '',
  city                    text default '',
  state                   text default '',
  postcode                text default '',
  country                 text default 'Malaysia',
  notes                   text default '',
  dentist                 text,
  consultant              text,
  outlet                  text,
  outlet_id               text,
  source                  text,
  opt_in_notifications    boolean default true,
  opt_in_marketing        boolean default true,
  is_vip                  boolean default false,
  preferred_language      text default 'English',
  case_notes_list         jsonb default '[]'::jsonb,
  join_date               text,
  created_at              timestamptz default now(),
  updated_at              timestamptz default now()
);

alter table patients enable row level security;
-- Allow full anon access (internal clinic app, no public-facing auth required)
drop policy if exists "anon_all" on patients;
create policy "anon_all" on patients for all using (true) with check (true);

-- ── 2. Add frontend-compatible columns to the existing `appointments` table ───
-- These columns use the same names the frontend sends (after snakify).
-- The existing start_time / end_time / customer_* columns remain for backward compat.

alter table appointments
  add column if not exists patient_id    text,
  add column if not exists patient_name  text,
  add column if not exists patient_phone text,
  add column if not exists dentist       text,
  add column if not exists service_code  text,
  add column if not exists outlet_name   text;

-- The `id` column is uuid — we generate proper UUIDs on the frontend now.
-- The `start_time` and `end_time` columns already exist and will receive the values.

-- ── 3. Grant anon full access to tables the frontend actively reads/writes ────
-- appointments
drop policy if exists "anon_all" on appointments;
create policy "anon_all" on appointments for all using (true) with check (true);

-- services (read-only seed, but upsert on init)
drop policy if exists "anon_all" on services;
create policy "anon_all" on services for all using (true) with check (true);

-- sales
drop policy if exists "anon_all" on sales;
create policy "anon_all" on sales for all using (true) with check (true);

-- employees
drop policy if exists "anon_all" on employees;
create policy "anon_all" on employees for all using (true) with check (true);

-- outlets
drop policy if exists "anon_all" on outlets;
create policy "anon_all" on outlets for all using (true) with check (true);

-- customers (existing table — keep accessible too)
drop policy if exists "anon_all" on customers;
create policy "anon_all" on customers for all using (true) with check (true);

-- ============================================================
-- FILE: 20260315000002_wa_booking_notes.sql
-- ============================================================
-- WhatsApp booking notes — shared across all browsers/devices
create table if not exists wa_booking_notes (
  id            text primary key,
  jid           text not null,
  appointment_id text,
  text          text,
  ts            bigint,
  created_at    timestamptz default now()
);

alter table wa_booking_notes enable row level security;
drop policy if exists "anon_all" on wa_booking_notes;
create policy "anon_all" on wa_booking_notes for all using (true) with check (true);

-- ============================================================
-- FILE: 20260325000001_time_blocks.sql
-- ============================================================
-- Time blocks: calendar holds without a patient (breaks, meetings, etc.)
alter table appointments
  add column if not exists is_time_block boolean default false,
  add column if not exists block_title text;

-- ============================================================
-- FILE: 20260326000001_appointments_drop_redundant_columns.sql
-- ============================================================
-- Remove duplicates of start/end, duration_min, and patient_phone.
alter table public.appointments
  drop column if exists date,
  drop column if exists "time",
  drop column if exists duration,
  drop column if exists phone;

-- ============================================================
-- FILE: 20260327000001_appointment_billing_items.sql
-- ============================================================
-- Line items billed against an appointment (catalog or ad-hoc). IDs are text to
-- match frontend appointment/service keys (e.g. apt-*, svc-*). No FK: local
-- schema may still use uuid PKs on parent tables while the app sends text ids.

create table if not exists public.appointment_billing_items (
  id uuid primary key default gen_random_uuid(),
  appointment_id text not null,
  service_id text,
  item_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(10,2) not null default 0,
  total numeric(10,2) generated always as (round((quantity::numeric * unit_price), 2)) stored,
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_appointment_billing_items_appointment_id
  on public.appointment_billing_items (appointment_id);

alter table public.appointment_billing_items enable row level security;

drop policy if exists "anon_all" on public.appointment_billing_items;
create policy "anon_all" on public.appointment_billing_items
  for all using (true) with check (true);

alter table public.sales add column if not exists appointment_id text;

-- ============================================================
-- FILE: 20260330000001_customer_code.sql
-- ============================================================
-- =============================================================================
-- Add customer_code to patients and appointments
-- =============================================================================

-- Patients: auto-generated code (e.g. CUS-000001), unique per patient
alter table patients
  add column if not exists customer_code text unique;

-- Appointments: denormalized from patients. NULL = lead (no registered patient)
alter table appointments
  add column if not exists customer_code text;

-- ============================================================
-- FILE: 20260330500000_auto_generate_ids.sql
-- ============================================================
-- Idempotent defaults so inserts can omit PKs (positions / role_permissions text; employees int identity).

alter table public.positions
  alter column id set default gen_random_uuid()::text;

alter table public.role_permissions
  alter column id set default gen_random_uuid()::text;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_attribute a
    where a.attrelid = 'public.employees'::regclass
      and a.attname = 'id'
      and a.attidentity in ('d', 'a')
  ) then
    alter table public.employees
      alter column id add generated by default as identity;
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.employees', 'id'),
  (select coalesce(max(id), 0) from public.employees)
);

-- ============================================================
-- FILE: 20260331120000_role_permission_flags.sql
-- ============================================================
-- Persist 50-column permission grid in role_permissions.permissions JSONB.
-- Shape: { "all": true } OR { "flags": [ bool × 50 ] } (see rolePermissionPermsFromJson in useStore).

UPDATE role_permissions SET permissions = '{"all": true}'::jsonb WHERE name = 'SYSTEM ADMIN';

UPDATE role_permissions SET permissions = '{"flags":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false]}'::jsonb WHERE name = 'ACCOUNT';

UPDATE role_permissions SET permissions = '{"flags":[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,true,true,true]}'::jsonb WHERE name = 'ADMIN';

UPDATE role_permissions SET permissions = '{"flags":[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,false,true,false,true,true,false,false,false,false,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]}'::jsonb WHERE name = 'DENTIST';

UPDATE role_permissions SET permissions = '{"flags":[false,false,false,false,true,true,true,true,true,true,true,true,true,true,false,false,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false]}'::jsonb WHERE name = 'MARKETING';

UPDATE role_permissions SET permissions = '{"flags":[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,false,false,false,false,false,false,false,true,false,true,true,true]}'::jsonb WHERE name = 'PART-TIME';

UPDATE role_permissions SET permissions = '{"flags":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]}'::jsonb WHERE name = 'BEAUTICIAN';

-- ============================================================
-- FILE: 20260331130000_appointments_start_end_columns.sql
-- ============================================================
-- App + exports use "start" / "end". Initial schema used start_time / end_time; rename when needed.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'appointments' and column_name = 'start_time'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'appointments' and column_name = 'start'
  ) then
    alter table public.appointments rename column start_time to start;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'appointments' and column_name = 'end_time'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'appointments' and column_name = 'end'
  ) then
    alter table public.appointments rename column end_time to "end";
  end if;
end $$;

-- ============================================================
-- FILE: 20260332000001_employees_fks_and_foundation.sql
-- ============================================================
-- One-shot: seed positions/roles (idempotent), wire employees to FKs only (position_id, role_id, outlet_id), drop legacy text columns.
-- Backfill from position/role text runs only if those columns still exist.
-- No demo employee deletes or hard-coded doctor rows — use the Employees UI or your own seed.sql for sample data.

-- ── Reference rows (idempotent) ───────────────────────────────────────────────
insert into public.positions (name)
select v.name
from (
  values
    ('ACCOUNTANT'),
    ('DENTAL ASSISTANT'),
    ('LOCUM DOCTOR'),
    ('MARKETING'),
    ('OPERATION'),
    ('RESIDENT DOCTOR'),
    ('STANDARD')
) as v(name)
where not exists (select 1 from public.positions p where p.name = v.name);

insert into public.role_permissions (name, permissions)
select v.name, v.perms::jsonb
from (
  values
    ('SYSTEM ADMIN', '{"all": true}'),
    ('ACCOUNT', '{}'),
    ('ADMIN', '{}'),
    ('DENTIST', '{}'),
    ('MARKETING', '{}'),
    ('PART-TIME', '{}'),
    ('BEAUTICIAN', '{}')
) as v(name, perms)
where not exists (select 1 from public.role_permissions r where r.name = v.name);

-- ── FK columns ──────────────────────────────────────────────────────────────
alter table public.employees
  add column if not exists position_id text,
  add column if not exists role_id text;

-- Only when legacy text columns exist (older DBs). Current prod had them removed already.
do $legacy$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'employees' and column_name = 'position'
  ) then
    execute $u$
      update public.employees e
      set position_id = p.id
      from public.positions p
      where e.position_id is null
        and e.position is not null
        and trim(e.position) <> ''
        and upper(trim(p.name)) = upper(trim(e.position))
    $u$;
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'employees' and column_name = 'role'
  ) then
    execute $u$
      update public.employees e
      set role_id = r.id
      from public.role_permissions r
      where e.role_id is null
        and e.role is not null
        and trim(e.role) <> ''
        and upper(trim(r.name)) = upper(trim(e.role))
    $u$;
  end if;
end;
$legacy$;

update public.employees
set outlet_id = null
where outlet_id is not null and trim(outlet_id) = '';

-- ── Foreign keys ─────────────────────────────────────────────────────────────
alter table public.employees
  drop constraint if exists employees_outlet_id_fkey,
  drop constraint if exists employees_position_id_fkey,
  drop constraint if exists employees_role_id_fkey;

alter table public.employees
  add constraint employees_outlet_id_fkey
    foreign key (outlet_id) references public.outlets (id) on delete set null,
  add constraint employees_position_id_fkey
    foreign key (position_id) references public.positions (id) on delete set null,
  add constraint employees_role_id_fkey
    foreign key (role_id) references public.role_permissions (id) on delete set null;

create index if not exists idx_employees_position_id on public.employees (position_id);
create index if not exists idx_employees_role_id on public.employees (role_id);

-- ── Remove legacy duplicate labels ──────────────────────────────────────────
alter table public.employees
  drop column if exists position,
  drop column if exists role,
  drop column if exists outlet;

-- ============================================================
-- FILE: 20260333000001_employees_email_gender.sql
-- ============================================================
-- Employees UI + useStore persist email and gender on create/update.
-- Idempotent for DBs that already had these columns from the initial schema.

alter table public.employees
  add column if not exists email text,
  add column if not exists gender text;

-- ============================================================
-- FILE: 20260334000001_customers_core_fks_retire_patients.sql
-- ============================================================
-- Core customer model: single public.customers table, FKs to outlets/employees/appointments/sales.
-- Retires public.patients when present (data copy + ID remap). Idempotent-friendly.

-- ── customers: home_outlet_id matches outlets.id (text) ──────────────────────
do $ctype$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'customers'
      and column_name = 'home_outlet_id' and udt_name = 'uuid'
  ) then
    alter table public.customers
      alter column home_outlet_id type text using (
        case when home_outlet_id is not null then home_outlet_id::text else null end
      );
  end if;
end;
$ctype$;

-- ── customers: consultant = employee integer id (was legacy uuid) ────────────
alter table public.customers drop column if exists consultant_id;
alter table public.customers
  add column consultant_id integer references public.employees(id) on delete set null;

-- ── Optional: migrate patients → customers ───────────────────────────────────
do $mig$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'patients'
  ) then
    create temporary table pat_cust_map (old_id text primary key, new_id uuid not null unique) on commit drop;

    insert into pat_cust_map (old_id, new_id)
    select p.id, gen_random_uuid() from public.patients p;

    insert into public.customers (
      id, name, first_name, last_name, salutation, gender,
      phone, phone2, email, date_of_birth, identification_no,
      membership_type, membership_no, customer_code,
      home_outlet_id, address1, address2, city, state, postcode, country,
      medical_notes, created_at, updated_at
    )
    select
      m.new_id,
      coalesce(nullif(trim(p.name), ''), 'Unknown'),
      nullif(trim(p.first_name), ''), nullif(trim(p.last_name), ''),
      nullif(trim(p.salutation), ''), nullif(trim(p.gender), ''),
      nullif(trim(p.phone), ''), nullif(trim(p.phone2), ''), nullif(trim(p.email), ''),
      case
        when p.dob is null or trim(p.dob) = '' then null
        when p.dob ~ '^\d{4}-\d{2}-\d{2}' then p.dob::date
        else null
      end,
      nullif(trim(p.identification_no), ''),
      coalesce(nullif(trim(p.membership_type), ''), 'No Membership'),
      nullif(trim(p.membership_no), ''),
      'CUS-' || replace(m.new_id::text, '-', ''),
      nullif(trim(p.outlet_id), ''),
      coalesce(nullif(trim(p.address1), ''), ''), coalesce(nullif(trim(p.address2), ''), ''),
      coalesce(nullif(trim(p.city), ''), ''), coalesce(nullif(trim(p.state), ''), ''),
      coalesce(nullif(trim(p.postcode), ''), ''),
      coalesce(nullif(trim(p.country), ''), 'Malaysia'),
      left(trim(coalesce(p.notes, '') || case when coalesce(trim(p.allergies), '') <> '' then E'\n' || p.allergies else '' end), 10000),
      coalesce(p.created_at, now()), coalesce(p.updated_at, now())
    from public.patients p
    join pat_cust_map m on m.old_id = p.id;

    update public.appointments a
    set customer_id = mp.new_id
    from pat_cust_map mp
    where a.patient_id is not null and trim(a.patient_id::text) = mp.old_id;

    if exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'sales' and column_name = 'patient_id'
    ) then
      execute '
        update public.sales s
        set customer_id = mp.new_id
        from pat_cust_map mp
        where s.patient_id is not null and trim(s.patient_id::text) = mp.old_id';
    end if;

    alter table public.appointments drop column if exists patient_id;
    alter table public.appointments drop column if exists patient_name;
    alter table public.appointments drop column if exists patient_phone;

    if exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'sales' and column_name = 'patient_id'
    ) then
      alter table public.sales drop column patient_id;
    end if;

    drop table public.patients;
  end if;
end;
$mig$;

-- ── sales: customer_id + customer_name (drop legacy patient_name) ─────────────
alter table public.sales add column if not exists customer_id uuid;
alter table public.sales add column if not exists customer_name text;

do $sales$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'sales' and column_name = 'patient_name'
  ) then
    execute 'update public.sales set customer_name = coalesce(customer_name, patient_name)';
    execute 'alter table public.sales drop column patient_name';
  end if;
end;
$sales$;

alter table public.sales drop column if exists patient_id;

-- ── Clear orphan FK values so constraints can validate ──────────────────────
update public.customers c
set home_outlet_id = null
where c.home_outlet_id is not null
  and not exists (select 1 from public.outlets o where o.id = c.home_outlet_id);

update public.appointments a
set customer_id = null
where a.customer_id is not null
  and not exists (select 1 from public.customers cu where cu.id = a.customer_id);

update public.sales s
set customer_id = null
where s.customer_id is not null
  and not exists (select 1 from public.customers cu where cu.id = s.customer_id);

-- ── Referential integrity (nullable FKs — leads / legacy rows still OK) ───────
alter table public.appointments drop constraint if exists appointments_customer_id_fkey;
alter table public.appointments
  add constraint appointments_customer_id_fkey
  foreign key (customer_id) references public.customers(id) on delete set null;

alter table public.customers drop constraint if exists customers_home_outlet_id_fkey;
alter table public.customers
  add constraint customers_home_outlet_id_fkey
  foreign key (home_outlet_id) references public.outlets(id) on delete set null;

alter table public.sales drop constraint if exists sales_customer_id_fkey;
alter table public.sales
  add constraint sales_customer_id_fkey
  foreign key (customer_id) references public.customers(id) on delete set null;

create index if not exists idx_customers_home_outlet on public.customers(home_outlet_id);
create index if not exists idx_customers_phone on public.customers(phone) where phone is not null and trim(phone) <> '';

-- ============================================================
-- FILE: 20260335000001_appointments_uuid_pk_and_relational_fks.sql
-- ============================================================
-- Appointments: uuid PK (was text holding uuid strings); FKs for outlet, service, employee.
-- Children: appointment_billing_items, sales, wa_booking_notes appointment_id → uuid.

alter table public.appointment_billing_items
  drop constraint if exists appointment_billing_items_appointment_id_fkey;

alter table public.sales
  drop constraint if exists sales_appointment_id_fkey;

alter table public.wa_booking_notes
  drop constraint if exists wa_booking_notes_appointment_id_fkey;

update public.appointments
set outlet_id = null
where outlet_id is not null and trim(outlet_id) = '';

update public.appointments
set service_id = null
where service_id is not null and trim(service_id) = '';

-- Cast to text before trim: appointment_id may already be uuid when re-running or after partial apply.
update public.sales
set appointment_id = null
where appointment_id is not null and trim(appointment_id::text) = '';

update public.sales s
set appointment_id = null
where s.appointment_id is not null and trim(s.appointment_id::text) <> ''
  and not exists (
    select 1 from public.appointments a where a.id::text = s.appointment_id::text
  );

update public.wa_booking_notes w
set appointment_id = null
where w.appointment_id is not null and trim(w.appointment_id::text) <> ''
  and not exists (
    select 1 from public.appointments a where a.id::text = w.appointment_id::text
  );

update public.wa_booking_notes
set appointment_id = null
where appointment_id is not null and trim(appointment_id::text) = '';

-- appointment_id is NOT NULL: drop rows that cannot reference an appointment.
delete from public.appointment_billing_items abi
where trim(abi.appointment_id::text) = ''
   or not exists (
    select 1 from public.appointments a where a.id::text = abi.appointment_id::text
  );

-- Orphans block FKs — clear first (matches 20260334000001 pattern).
update public.appointments a
set outlet_id = null
where a.outlet_id is not null
  and not exists (select 1 from public.outlets o where o.id = a.outlet_id);

update public.appointments a
set service_id = null
where a.service_id is not null
  and not exists (select 1 from public.services s where s.id = a.service_id);

update public.appointments a
set employee_id = null
where a.employee_id is not null
  and not exists (select 1 from public.employees e where e.id = a.employee_id);

alter table public.appointments
  alter column id drop default,
  alter column id type uuid using id::uuid,
  alter column id set default gen_random_uuid();

alter table public.appointment_billing_items
  alter column appointment_id type uuid using appointment_id::uuid;

alter table public.sales
  alter column appointment_id type uuid using appointment_id::uuid;

alter table public.wa_booking_notes
  alter column appointment_id type uuid using appointment_id::uuid;

alter table public.appointment_billing_items
  drop constraint if exists appointment_billing_items_appointment_id_fkey;
alter table public.appointment_billing_items
  add constraint appointment_billing_items_appointment_id_fkey
  foreign key (appointment_id) references public.appointments(id) on delete cascade;

alter table public.sales
  drop constraint if exists sales_appointment_id_fkey;
alter table public.sales
  add constraint sales_appointment_id_fkey
  foreign key (appointment_id) references public.appointments(id) on delete set null;

alter table public.wa_booking_notes
  drop constraint if exists wa_booking_notes_appointment_id_fkey;
alter table public.wa_booking_notes
  add constraint wa_booking_notes_appointment_id_fkey
  foreign key (appointment_id) references public.appointments(id) on delete set null;

alter table public.appointments drop constraint if exists appointments_outlet_id_fkey;
alter table public.appointments
  add constraint appointments_outlet_id_fkey
  foreign key (outlet_id) references public.outlets(id) on delete set null;

alter table public.appointments drop constraint if exists appointments_service_id_fkey;
alter table public.appointments
  add constraint appointments_service_id_fkey
  foreign key (service_id) references public.services(id) on delete set null;

alter table public.appointments drop constraint if exists appointments_employee_id_fkey;
alter table public.appointments
  add constraint appointments_employee_id_fkey
  foreign key (employee_id) references public.employees(id) on delete set null;

create index if not exists idx_appointments_outlet_id on public.appointments(outlet_id);
create index if not exists idx_appointments_service_id on public.appointments(service_id);
create index if not exists idx_appointments_employee_id on public.appointments(employee_id);

-- ============================================================
-- FILE: 20260401000001_sequential_customer_codes.sql
-- ============================================================
-- Migrate UUID-based customer_codes to sequential CUS-000001 format.
-- Skips customers that already have a valid sequential code (CUS- followed by digits only).
-- New numbers start after the highest existing sequential code.

with max_existing as (
  -- Find the highest number among already-sequential codes
  select coalesce(max(regexp_replace(customer_code, '\D', '', 'g')::bigint), 0) as max_num
  from public.customers
  where customer_code ~ '^CUS-\d+$'
),
to_fix as (
  -- Only customers whose code is NOT already sequential (i.e. contains hex/uuid chars)
  select id, created_at,
         row_number() over (order by created_at, id) as rn
  from public.customers
  where customer_code !~ '^CUS-\d+$'
),
numbered as (
  select tf.id,
         'CUS-' || lpad((me.max_num + tf.rn)::text, 6, '0') as new_code
  from to_fix tf
  cross join max_existing me
)
update public.customers c
set customer_code = n.new_code
from numbered n
where c.id = n.id;

-- Also update the denormalised customer_code on appointments
update public.appointments a
set customer_code = c.customer_code
from public.customers c
where a.customer_id = c.id
  and a.customer_code is distinct from c.customer_code;

-- ============================================================
-- FILE: 20260404000001_outlets_cleanup_reseed.sql
-- ============================================================
-- =============================================================================
-- Outlets: convert from text PK to uuid PK, keep it simple.
-- =============================================================================

-- ── 1. Drop FK constraints referencing outlets(id) ──────────────────────────
alter table public.employees     drop constraint if exists employees_outlet_id_fkey;
alter table public.customers     drop constraint if exists customers_home_outlet_id_fkey;
alter table public.appointments  drop constraint if exists appointments_outlet_id_fkey;

-- ── 2. Null out all outlet references (old text IDs will be invalid) ────────
update public.employees     set outlet_id = null       where outlet_id is not null;
update public.customers     set home_outlet_id = null   where home_outlet_id is not null;
update public.appointments  set outlet_id = null        where outlet_id is not null;

-- ── 3. Drop and recreate outlets with uuid PK ──────────────────────────────
drop table if exists public.outlets cascade;

create table public.outlets (
  id         uuid primary key default gen_random_uuid(),
  code       text,
  name       text not null,
  brand_id   text not null default 'brand-big-dental',
  is_active  boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.outlets enable row level security;
drop policy if exists "anon_all" on public.outlets;
create policy "anon_all" on public.outlets for all using (true) with check (true);

create trigger trg_outlets_updated_at
  before update on public.outlets for each row execute function update_updated_at();

-- ── 4. Convert outlet_id columns from text → uuid ──────────────────────────
alter table public.employees
  alter column outlet_id type uuid using null;

alter table public.customers
  alter column home_outlet_id type uuid using null;

do $atype$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'appointments'
      and column_name = 'outlet_id' and udt_name <> 'uuid'
  ) then
    alter table public.appointments
      alter column outlet_id type uuid using null;
  end if;
end;
$atype$;

-- ── 5. Re-add FK constraints ────────────────────────────────────────────────
alter table public.employees
  add constraint employees_outlet_id_fkey
  foreign key (outlet_id) references public.outlets(id) on delete set null;

alter table public.customers
  add constraint customers_home_outlet_id_fkey
  foreign key (home_outlet_id) references public.outlets(id) on delete set null;

alter table public.appointments
  add constraint appointments_outlet_id_fkey
  foreign key (outlet_id) references public.outlets(id) on delete set null;

-- ── 6. Two sample outlets ───────────────────────────────────────────────────
insert into public.outlets (code, name, brand_id) values
  ('KD1', 'KumoDent Main Clinic', 'brand-big-dental'),
  ('KD2', 'KumoDent Branch',      'brand-big-dental');

-- ============================================================
-- FILE: 20260406000001_employee_outlets_and_rooms.sql
-- ============================================================
-- =============================================================================
-- 1. employee_outlets junction table (many-to-many: employees ↔ outlets)
-- 2. Drop employees.outlet_id (replaced by junction table)
-- 3. rooms column on outlets (per-outlet treatment rooms)
-- =============================================================================

-- ── 1. Junction table ─────────────────────────────────────────────────────────
create table if not exists public.employee_outlets (
  employee_id uuid not null references public.employees(id) on delete cascade,
  outlet_id   uuid not null references public.outlets(id)   on delete cascade,
  created_at  timestamptz default now(),
  primary key (employee_id, outlet_id)
);

alter table public.employee_outlets enable row level security;
drop policy if exists "anon_all" on public.employee_outlets;
create policy "anon_all" on public.employee_outlets for all using (true) with check (true);

-- Migrate existing outlet_id data into the junction table before dropping
insert into public.employee_outlets (employee_id, outlet_id)
select id, outlet_id
from public.employees
where outlet_id is not null
on conflict do nothing;

-- ── 2. Drop outlet_id from employees ─────────────────────────────────────────
alter table public.employees
  drop constraint if exists employees_outlet_id_fkey;

alter table public.employees
  drop column if exists outlet_id;

-- ── 3. Per-outlet rooms ───────────────────────────────────────────────────────
alter table public.outlets
  add column if not exists rooms text[];

-- ============================================================
-- FILE: 20260406000002_positions_roles_uuid_pks.sql
-- ============================================================
-- Convert positions.id and role_permissions.id from TEXT to UUID.
-- Some existing rows have non-UUID IDs (e.g. "role-1", "pos-1") so we replace
-- them with real UUIDs first, then convert the column type.
-- Also ensure positions has a status column for Active/Inactive toggling.

-- ── 1. Drop FK constraints on employees that reference these tables ──────────
alter table public.employees
  drop constraint if exists employees_position_id_fkey,
  drop constraint if exists employees_role_id_fkey;

-- ── 2. Replace non-UUID ids with real UUIDs ─────────────────────────────────
-- For each non-UUID position id, generate a new UUID and update employees too.
do $$
declare
  r record;
  new_id text;
begin
  for r in
    select id from public.positions
    where id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  loop
    new_id := gen_random_uuid()::text;
    update public.employees set position_id = new_id where position_id = r.id;
    update public.positions set id = new_id where id = r.id;
  end loop;

  for r in
    select id from public.role_permissions
    where id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  loop
    new_id := gen_random_uuid()::text;
    update public.employees set role_id = new_id where role_id = r.id;
    update public.role_permissions set id = new_id where id = r.id;
  end loop;
end $$;

-- Also clear any employee FK values that don't match an existing row
update public.employees set position_id = null
  where position_id is not null
    and position_id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';

update public.employees set role_id = null
  where role_id is not null
    and role_id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';

-- ── 3. Convert positions.id TEXT → UUID ─────────────────────────────────────
alter table public.positions
  alter column id set default null;

alter table public.positions
  alter column id type uuid using id::uuid;

alter table public.positions
  alter column id set default gen_random_uuid();

-- ── 4. Convert role_permissions.id TEXT → UUID ──────────────────────────────
alter table public.role_permissions
  alter column id set default null;

alter table public.role_permissions
  alter column id type uuid using id::uuid;

alter table public.role_permissions
  alter column id set default gen_random_uuid();

-- ── 5. Convert FK columns on employees TEXT → UUID ──────────────────────────
alter table public.employees
  alter column position_id type uuid using position_id::uuid;

alter table public.employees
  alter column role_id type uuid using role_id::uuid;

-- ── 6. Re-add foreign key constraints ───────────────────────────────────────
alter table public.employees
  add constraint employees_position_id_fkey
    foreign key (position_id) references public.positions (id) on delete set null,
  add constraint employees_role_id_fkey
    foreign key (role_id) references public.role_permissions (id) on delete set null;

-- ── 7. Ensure positions has a status column ─────────────────────────────────
alter table public.positions
  add column if not exists status text not null default 'Active';

-- ── 8. Drop stale employee_count column (now computed from employees) ───────
alter table public.positions
  drop column if exists employee_count;

-- ============================================================
-- FILE: 20260406000003_employee_extra_columns.sql
-- ============================================================
-- Add columns the Employee form needs that may be missing from the initial schema.
-- Idempotent: uses "add column if not exists".

alter table public.employees
  add column if not exists phone          text,
  add column if not exists phone2         text,
  add column if not exists address1       text default '',
  add column if not exists address2       text default '',
  add column if not exists address3       text default '',
  add column if not exists postcode       text default '',
  add column if not exists appt_seq       int;

-- ============================================================
-- FILE: 20260406000004_employee_shifts.sql
-- ============================================================
-- Employee working-hours / shift templates.
-- Each row represents a recurring (or one-off) shift for an employee on a given weekday.

create table if not exists public.employee_shifts (
  id            uuid primary key default gen_random_uuid(),
  employee_id   uuid not null references public.employees(id) on delete cascade,
  outlet_id     uuid not null references public.outlets(id) on delete cascade,
  day_of_week   int  not null check (day_of_week between 0 and 6),  -- 0=Mon .. 6=Sun
  shift_date    date,             -- set when repeat_type='none' (the specific date)
  start_time    time not null default '09:00',
  end_time      time not null default '18:00',
  is_overnight  boolean default false,
  repeat_type   text default 'weekly' check (repeat_type in ('none','weekly')),
  repeat_end    date,            -- NULL = ongoing (only used when repeat_type='weekly')
  breaks        jsonb default '[]',  -- [{start:"HH:mm", end:"HH:mm"}, ...]
  remarks       text default '',
  is_active     boolean default true,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

create index if not exists idx_employee_shifts_employee on public.employee_shifts(employee_id);
create index if not exists idx_employee_shifts_outlet   on public.employee_shifts(outlet_id);

alter table public.employee_shifts enable row level security;
drop policy if exists "anon_all" on public.employee_shifts;
create policy "anon_all" on public.employee_shifts for all using (true) with check (true);

-- ============================================================
-- FILE: 20260406000005_employee_missing_columns.sql
-- ============================================================
-- Add missing columns to employees table.
-- Actual DB has: address1-3, appt_seq, bookable, brand_id, created_at, email,
--   gender, id, kumosan, last_active, name, online_bookable, phone, phone2,
--   position_id, postcode, role_id, salutation, shifts, web_login
-- Missing: identification_no, date_of_birth, start_date, country, state, city,
--   sales_target, is_active, employee_code, updated_at

alter table public.employees
  add column if not exists identification_no  text,
  add column if not exists date_of_birth      date,
  add column if not exists start_date         date,
  add column if not exists country            text default 'Malaysia',
  add column if not exists state              text,
  add column if not exists city               text,
  add column if not exists sales_target       numeric(10,2) default 0,
  add column if not exists is_active          boolean default true,
  add column if not exists employee_code      text,
  add column if not exists updated_at         timestamptz default now();

-- ============================================================
-- FILE: 20260407000001_customer_medical_conditions.sql
-- ============================================================
-- Add medical_conditions column (JSONB array of condition strings)
ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS medical_conditions JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.customers.medical_conditions IS 'Array of known medical conditions (structured checklist)';

-- ============================================================
-- FILE: 20260407000002_ensure_case_notes_table.sql
-- ============================================================
-- Ensure case_notes table exists (may have been missed if initial migration was partial)
create table if not exists case_notes (
  id               uuid primary key default gen_random_uuid(),
  appointment_id   uuid references appointments(id),
  customer_id      uuid references customers(id),
  customer_name    text,
  membership_no    text,
  note_date        date,
  note_time        time,
  content          text,
  employee_id      uuid references employees(id),
  created_by       text,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

-- Ensure RLS
alter table case_notes enable row level security;

-- Ensure RLS policy (drop + recreate to be idempotent)
do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'case_notes' and policyname = 'Authenticated full access'
  ) then
    create policy "Authenticated full access" on case_notes for all using (auth.role() = 'authenticated');
  end if;
end $$;

-- Ensure updated_at trigger
create or replace function update_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql;

drop trigger if exists trg_case_notes_updated_at on case_notes;
create trigger trg_case_notes_updated_at
  before update on case_notes for each row execute function update_updated_at();

-- Reload PostgREST schema cache
notify pgrst, 'reload schema';

-- ============================================================
-- FILE: 20260407000003_case_notes_anon_policy.sql
-- ============================================================
-- Allow anon access to case_notes (matches other tables in frontend_compat)
create policy "anon_all" on case_notes for all using (true) with check (true);

notify pgrst, 'reload schema';
