export const DEFAULT_COUNTRY_CODE = "MY";

export const COUNTRIES: ReadonlyArray<{ code: string; name: string }> = [
	{ code: "MY", name: "Malaysia" },
	{ code: "SG", name: "Singapore" },
	{ code: "ID", name: "Indonesia" },
	{ code: "TH", name: "Thailand" },
	{ code: "PH", name: "Philippines" },
	{ code: "VN", name: "Vietnam" },
	{ code: "BN", name: "Brunei" },
	{ code: "KH", name: "Cambodia" },
	{ code: "LA", name: "Laos" },
	{ code: "MM", name: "Myanmar" },
	{ code: "TL", name: "Timor-Leste" },
	{ code: "CN", name: "China" },
	{ code: "HK", name: "Hong Kong" },
	{ code: "TW", name: "Taiwan" },
	{ code: "MO", name: "Macau" },
	{ code: "JP", name: "Japan" },
	{ code: "KR", name: "South Korea" },
	{ code: "KP", name: "North Korea" },
	{ code: "MN", name: "Mongolia" },
	{ code: "IN", name: "India" },
	{ code: "PK", name: "Pakistan" },
	{ code: "BD", name: "Bangladesh" },
	{ code: "LK", name: "Sri Lanka" },
	{ code: "NP", name: "Nepal" },
	{ code: "BT", name: "Bhutan" },
	{ code: "MV", name: "Maldives" },
	{ code: "AF", name: "Afghanistan" },
	{ code: "IR", name: "Iran" },
	{ code: "IQ", name: "Iraq" },
	{ code: "IL", name: "Israel" },
	{ code: "PS", name: "Palestine" },
	{ code: "JO", name: "Jordan" },
	{ code: "LB", name: "Lebanon" },
	{ code: "SY", name: "Syria" },
	{ code: "SA", name: "Saudi Arabia" },
	{ code: "AE", name: "United Arab Emirates" },
	{ code: "QA", name: "Qatar" },
	{ code: "BH", name: "Bahrain" },
	{ code: "KW", name: "Kuwait" },
	{ code: "OM", name: "Oman" },
	{ code: "YE", name: "Yemen" },
	{ code: "TR", name: "Turkey" },
	{ code: "CY", name: "Cyprus" },
	{ code: "AM", name: "Armenia" },
	{ code: "AZ", name: "Azerbaijan" },
	{ code: "GE", name: "Georgia" },
	{ code: "KZ", name: "Kazakhstan" },
	{ code: "KG", name: "Kyrgyzstan" },
	{ code: "TJ", name: "Tajikistan" },
	{ code: "TM", name: "Turkmenistan" },
	{ code: "UZ", name: "Uzbekistan" },
	{ code: "RU", name: "Russia" },
	{ code: "UA", name: "Ukraine" },
	{ code: "BY", name: "Belarus" },
	{ code: "MD", name: "Moldova" },
	{ code: "PL", name: "Poland" },
	{ code: "CZ", name: "Czech Republic" },
	{ code: "SK", name: "Slovakia" },
	{ code: "HU", name: "Hungary" },
	{ code: "RO", name: "Romania" },
	{ code: "BG", name: "Bulgaria" },
	{ code: "RS", name: "Serbia" },
	{ code: "HR", name: "Croatia" },
	{ code: "SI", name: "Slovenia" },
	{ code: "BA", name: "Bosnia and Herzegovina" },
	{ code: "ME", name: "Montenegro" },
	{ code: "MK", name: "North Macedonia" },
	{ code: "AL", name: "Albania" },
	{ code: "XK", name: "Kosovo" },
	{ code: "GR", name: "Greece" },
	{ code: "IT", name: "Italy" },
	{ code: "MT", name: "Malta" },
	{ code: "SM", name: "San Marino" },
	{ code: "VA", name: "Vatican City" },
	{ code: "ES", name: "Spain" },
	{ code: "PT", name: "Portugal" },
	{ code: "AD", name: "Andorra" },
	{ code: "FR", name: "France" },
	{ code: "MC", name: "Monaco" },
	{ code: "BE", name: "Belgium" },
	{ code: "NL", name: "Netherlands" },
	{ code: "LU", name: "Luxembourg" },
	{ code: "DE", name: "Germany" },
	{ code: "AT", name: "Austria" },
	{ code: "CH", name: "Switzerland" },
	{ code: "LI", name: "Liechtenstein" },
	{ code: "GB", name: "United Kingdom" },
	{ code: "IE", name: "Ireland" },
	{ code: "IS", name: "Iceland" },
	{ code: "NO", name: "Norway" },
	{ code: "SE", name: "Sweden" },
	{ code: "FI", name: "Finland" },
	{ code: "DK", name: "Denmark" },
	{ code: "EE", name: "Estonia" },
	{ code: "LV", name: "Latvia" },
	{ code: "LT", name: "Lithuania" },
	{ code: "CA", name: "Canada" },
	{ code: "US", name: "United States" },
	{ code: "MX", name: "Mexico" },
	{ code: "GT", name: "Guatemala" },
	{ code: "BZ", name: "Belize" },
	{ code: "SV", name: "El Salvador" },
	{ code: "HN", name: "Honduras" },
	{ code: "NI", name: "Nicaragua" },
	{ code: "CR", name: "Costa Rica" },
	{ code: "PA", name: "Panama" },
	{ code: "CU", name: "Cuba" },
	{ code: "JM", name: "Jamaica" },
	{ code: "HT", name: "Haiti" },
	{ code: "DO", name: "Dominican Republic" },
	{ code: "PR", name: "Puerto Rico" },
	{ code: "TT", name: "Trinidad and Tobago" },
	{ code: "BB", name: "Barbados" },
	{ code: "BS", name: "Bahamas" },
	{ code: "CO", name: "Colombia" },
	{ code: "VE", name: "Venezuela" },
	{ code: "GY", name: "Guyana" },
	{ code: "SR", name: "Suriname" },
	{ code: "EC", name: "Ecuador" },
	{ code: "PE", name: "Peru" },
	{ code: "BO", name: "Bolivia" },
	{ code: "BR", name: "Brazil" },
	{ code: "PY", name: "Paraguay" },
	{ code: "UY", name: "Uruguay" },
	{ code: "AR", name: "Argentina" },
	{ code: "CL", name: "Chile" },
	{ code: "AU", name: "Australia" },
	{ code: "NZ", name: "New Zealand" },
	{ code: "PG", name: "Papua New Guinea" },
	{ code: "FJ", name: "Fiji" },
	{ code: "SB", name: "Solomon Islands" },
	{ code: "VU", name: "Vanuatu" },
	{ code: "NC", name: "New Caledonia" },
	{ code: "PF", name: "French Polynesia" },
	{ code: "WS", name: "Samoa" },
	{ code: "TO", name: "Tonga" },
	{ code: "KI", name: "Kiribati" },
	{ code: "TV", name: "Tuvalu" },
	{ code: "NR", name: "Nauru" },
	{ code: "PW", name: "Palau" },
	{ code: "FM", name: "Micronesia" },
	{ code: "MH", name: "Marshall Islands" },
	{ code: "EG", name: "Egypt" },
	{ code: "LY", name: "Libya" },
	{ code: "TN", name: "Tunisia" },
	{ code: "DZ", name: "Algeria" },
	{ code: "MA", name: "Morocco" },
	{ code: "SD", name: "Sudan" },
	{ code: "SS", name: "South Sudan" },
	{ code: "ET", name: "Ethiopia" },
	{ code: "ER", name: "Eritrea" },
	{ code: "DJ", name: "Djibouti" },
	{ code: "SO", name: "Somalia" },
	{ code: "KE", name: "Kenya" },
	{ code: "UG", name: "Uganda" },
	{ code: "RW", name: "Rwanda" },
	{ code: "BI", name: "Burundi" },
	{ code: "TZ", name: "Tanzania" },
	{ code: "MW", name: "Malawi" },
	{ code: "MZ", name: "Mozambique" },
	{ code: "ZM", name: "Zambia" },
	{ code: "ZW", name: "Zimbabwe" },
	{ code: "BW", name: "Botswana" },
	{ code: "NA", name: "Namibia" },
	{ code: "ZA", name: "South Africa" },
	{ code: "LS", name: "Lesotho" },
	{ code: "SZ", name: "Eswatini" },
	{ code: "AO", name: "Angola" },
	{ code: "CG", name: "Republic of the Congo" },
	{ code: "CD", name: "DR Congo" },
	{ code: "CF", name: "Central African Republic" },
	{ code: "CM", name: "Cameroon" },
	{ code: "GQ", name: "Equatorial Guinea" },
	{ code: "GA", name: "Gabon" },
	{ code: "ST", name: "São Tomé and Príncipe" },
	{ code: "TD", name: "Chad" },
	{ code: "NE", name: "Niger" },
	{ code: "NG", name: "Nigeria" },
	{ code: "BJ", name: "Benin" },
	{ code: "TG", name: "Togo" },
	{ code: "GH", name: "Ghana" },
	{ code: "BF", name: "Burkina Faso" },
	{ code: "CI", name: "Côte d'Ivoire" },
	{ code: "LR", name: "Liberia" },
	{ code: "SL", name: "Sierra Leone" },
	{ code: "GN", name: "Guinea" },
	{ code: "GW", name: "Guinea-Bissau" },
	{ code: "SN", name: "Senegal" },
	{ code: "GM", name: "Gambia" },
	{ code: "ML", name: "Mali" },
	{ code: "MR", name: "Mauritania" },
	{ code: "CV", name: "Cape Verde" },
	{ code: "MG", name: "Madagascar" },
	{ code: "MU", name: "Mauritius" },
	{ code: "SC", name: "Seychelles" },
	{ code: "KM", name: "Comoros" },
];

export const COUNTRY_CODES = COUNTRIES.map((c) => c.code) as ReadonlyArray<
	(typeof COUNTRIES)[number]["code"]
>;

const COUNTRY_NAME_BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c.name]));

export function countryNameForCode(code: string | null | undefined): string {
	if (!code) return "—";
	return COUNTRY_NAME_BY_CODE.get(code.toUpperCase()) ?? code;
}

export function isValidCountryCode(value: string | null | undefined): boolean {
	if (!value) return false;
	return COUNTRY_NAME_BY_CODE.has(value.toUpperCase());
}
